### ISSUE TITLE
Замечания по lw2/task1

### ISSUE THREAD

**Issue by ivklgn** [Zybera/web-development-course#1]
<img width="874" alt="Снимок экрана 2021-03-01 в 13 03 02" src="https://user-images.githubusercontent.com/15219574/109481943-76158a80-7a8e-11eb-8f61-abd3466941ed.png">

проблема с выравниванием

**Comment by ivklgn** [comment]
```html
            <a href="!#" class="item-btn">Small Button</a>
```

лучше

```html
            <a href="#" class="item-btn">Small Button</a>
```

**Comment by ivklgn** [comment]
```html
        <div class="header-title-item1">Our</div>
        <div class="header-title-item2">Programs</div>
```

это inline элементы и тут не подойдет 2 div блока, но тут больше что то типа:

```html
<h1>Our <span>Programs</span></h1>
```

**Comment by ivklgn** [comment]
в css есть нарушение форматирования

**Comment by ivklgn** [comment]
```css

@font-face {
  font-family: JosefinSans-Regular; /* Имя шрифта */
  src: url(../fonts/JosefinSans-Regular.ttf); /* Путь к файлу со шрифтом */
}
@font-face {
   font-family: JosefinSans-Bold; /* Имя шрифта */
   src: url(../fonts/JosefinSans-Bold.ttf); /* Путь к файлу со шрифтом */
}

```

обычно глобальные настройки отображения помещаются в начало документа

**Comment by ivklgn** [comment]
ради выравнивания текста внутри кнопки не нужно делать ее flex-контейнером:

```css
.item-btn {
  margin: 16px 0px 0px 0px;
  background: #EC6041;
  box-shadow:  4px 4px 0px 0px #F1876F, 8px 8px 0px 0px #F5AE9E;
  text-decoration: none;
  color: #FFFFFF;
  width: 144px;
  height: 36px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 14px;
  line-height: 20px;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  font-family: JosefinSans-Regular;
  font-weight: bold;
}
```

воспользуйтесь свойствами типа text-align и подобными
