### ISSUE TITLE
Замечания по lw4/task2

### ISSUE THREAD

**Issue by ivklgn** [Zybera/web-development-course#4]
в БЭМ не применяется доступ к дочерним селекторам:

```css
.task--completed {
  order: 5;
  text-decoration: line-through;
  color: #CED3FF;
}

.task--completed .task__name {
  color: #CED3FF;
}

.task--completed .task__time {
  display: none;
}
```

в вашем случае модификатор должен быть у элемента task__name
